### ISSUE TITLE
Consider SassDoc comments

### ISSUE THREAD

**Issue by KittyGiraudel** [mknadler/randomize.scss#2]
In order to document the public API, I suppose you could consider using SassDoc. I'd be happy to help.

**Comment by mknadler** [comment]
I'm working on them & will be adding them in shortly.

Did the default theme change, by the way? I was expecting pink :p

**Comment by KittyGiraudel** [comment]
It depends on which version of SassDoc you are running. If you run a RC of v2, yep, the theme's changed.

**Comment by mknadler** [comment]
Gotcha, thanks :)
