### ISSUE TITLE
Make $decimal a boolean

### ISSUE THREAD

**Issue by KittyGiraudel** [mknadler/randomize.scss#3]
Don't allow `$decimal` to be `"decimal"` as well. Loose typing is usually the source of all sorts of troubles. Force it as a boolean.

**Comment by mknadler** [comment]
Do you mind explaining this further? I'm sure that harm could come of having it in it's current state, but I'm not exactly sure what that harm would look like.

By way of explanation for why I have `decimal` there at all: originally, I was going to leave it as a boolean; I added `decimal` in an attempt to make it more user-friendly. I figured calling `height: random-between(10, 15, decimal)` might be easier to remember (and therefore easier to use) than calling `height: random-between(10, 15, true)`.

I just had an idea for a third option, and I'm not sure if it's a good one or not, but: splitting the decimal functionality off into a new function, `@function random-decimal-between`. This could potentially smooth over ease-of-use concerns.

**Comment by KittyGiraudel** [comment]
I get your point, and it makes perfect sense. Now, you have a couple of option to work-around it. 

Either you can leave it this way but I do think having a parameter that can be either a very specific string or a boolean is a bad idea because it is loosely typed. Not only does it require extra code, but it is likely to cause confusion to developers.

You could make this parameter a boolean and a boolean only, then leave to the API documentation and inline comments the role to explain what is this parameter and how does it work. Having it as a strict boolean make it easier to use. Not that you can also name your parameter when using your function, such as:

``` scss
height: random-between(10, 15, $decimal: true);
```

Or as you said, and I think it is a perfectly valid idea since you are building a public API, add an extra function to circumvent the whole thing. Better API, easier to use. Nothing but the best.

**Comment by mknadler** [comment]
Fixed in 2cc3fa3b9d5d1c250ad801394653eee90cfa5a77
