### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by KittyGiraudel** [mknadler/randomize.scss#6]
Are you interested in me submitting a PR to improve code quality in order to stick to http://sass-guidelin.es?

**Comment by mknadler** [comment]
So that I can develop more consistent writing habits, I think I'd prefer to do this myself, at least at first? Especially as I'll be making commits incorporating some of the other suggested changes, anyways. If I still have quality inconsistencies after that point, though, by all means!

**Comment by KittyGiraudel** [comment]
Sure. Sass Guidelines is a good start _at least to me_, because it enforces consistency. Again, specifics are irrelevant, only consistency is key.

Also, may I suggest to extensively use empty lines. Empty lines do not make the code longer, they make it cleaner and easier to read. I also tend to add extra empty lines between two mixins/functions/whatever, like 5 to make it quite clear they are different items.

**Comment by mknadler** [comment]
Okay, this is what I've got in terms of code quality revision: 5007ca042927458a452efd1226c6107fc2b3c641

**Comment by KittyGiraudel** [comment]
Use `not` rather than `!= true`.
