### ISSUE TITLE
Use a keyframes mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [mknadler/randomize.scss#9]
It is quite ugly having to repeat the logic twice within `random-animate`. Either you should drop prefixes altogether, or use a mixin to output keyframes.

**Comment by mknadler** [comment]
Agreed! This is something I've spent a while trying to figure out how to implement. Not much luck.

Specifically, I haven't been able to figure out how to either interpolate the `@` keyword or interpolate `-webkit-` after the `@` keyword without getting an error thrown.

Related issue: https://github.com/sass/sass/issues/429

**Comment by KittyGiraudel** [comment]
Keep it simple Miriam. The only prefix that is still needed is `-webkit-`. There is no need to interpolate anything.

``` scss
@mixin keyframes($name) {
  @-webkit-keyframes #{$name} {
    @content;
  }

  @keyframes #{$name} {
    @content;
  }
}
```

**Comment by mknadler** [comment]
_sigh_

Yup, that works. Might be time to start a new file for generic helpers/utilities.
